import datetime
import EmailStr
from pydantic import BaseModel, EmailStr, Field

class Ticket(BaseModel):
    id: str = Field(..., description="Unique identifier for the ticket")
    summary: str = Field(..., description="Brief summary of the ticket")
    description: str = Field(..., description="Detailed description of the ticket")
    reporter: EmailStr = Field(..., description="Person who reported the ticket")
    created_at: datetime = Field(..., description="Timestamp of when the ticket was created")
    type: Literal['Bug', 'Feature', 'Task', 'Support'] = Field(..., description="Type of the ticket")

class TriagedTicket(Ticket):
    ai_category: Literal['Access', 'Billing', 'Technical', 'Other'] = Field(..., description="Category assigned by AI triage system")
    ai_priority: Literal['High', 'Medium', 'Low'] = Field(..., description="Priority assigned by AI triage system")
    ai_summary: str = Field(min_length=10, max_length=200, description="Summary generated by AI triage system")
    ai_escalate: bool = Field(..., description="Whether the ticket should be escalated based on AI triage system")
    ai_confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of the AI triage system's categorization and prioritization")
    processed_at: datetime = Field(..., description="Timestamp of when the ticket was processed by the AI triage system")